global:
  scrape_interval: 15s

rule_files:
  - /etc/prometheus/rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "trainer"
    metrics_path: /metrics
    static_configs:
      - targets: ["trainer:8000"]

  - job_name: "tester"
    metrics_path: /metrics
    static_configs:
      - targets: ["tester:8001"]

  - job_name: "pushgateway"
    static_configs:
      - targets: ["pushgateway:9091"]

  # Optional (only enable when Minikube is running and stable)
  # - job_name: "ai-augmented-devops-k8s"
  #   scrape_interval: 60s
  #   scrape_timeout: 5s
  #   metrics_path: /metrics
  #   static_configs:
  #     - targets: ["192.168.49.2:30080"]
