apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-augmented-devops
  labels:
    app: ai-augmented-devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-augmented-devops
  template:
    metadata:
      labels:
        app: ai-augmented-devops
    spec:
      containers:
        - name: ai-app
          image: ggyabaah/ai-augmented-devops:latest   # <-- replace with your actual Docker Hub repo
          imagePullPolicy: Always                    # ensures you always get the newest pushed image
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"